- name: Backend Setup
  hosts: all
  becomes: yes
  tasks:
    - name: Install NodeJs
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
    - name: Install nodeJS
      ansible.builtin.dnf:
        name: nodejs
    - name: Copy Backend Service File
      ansible.builtin.copy:
        srv: backend.service
        dest: /etc/systemd/system/backend.service
    - name: Add the Application user
      ansible.builtin.user:
        name: expense
    - name: Clean of old content
      ansible.builtin.file:
        path: /app
        state: absent
    - name: Create a directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: Download backend code and Extract
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes
    - name: Install NodeJS dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app
    - name: install MYSQL Client
      ansible.builtin.dnf:
        name: mysql
    - name: Load schema
      ansible.builtin.shell: mysql -h mysql.baseed.online mysql -uroot -pExpenseApp@1 < /app/schema/backend.sql
    - name: start backend service
      ansible.builtin.systemd:
        name: backend
        state: restated
        enabled: yes
        daemon-reload: yes




