  - name: Installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: placing Expense config file
    ansible.builtin.template:
      src: expense.conf
      dest: /etc/nginx/default.d

  - name: Include App Pre-requisites
    ansible.builtin.import_role:
      name: common
      tasks_from: app_prereq

  - name: Restarting nginx service
    ansible.builtin.systemd:
      name: nginx
      state: restarted
      enabled: yes